# Generated by Django 4.1.7 on 2023-04-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permanencias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.TextField(max_length=200)),
                ('pais', models.TextField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('actividad', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=200)),
                ('estudios', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('tit_dep', models.CharField(max_length=4)),
                ('autoridad', models.CharField(max_length=400)),
                ('beneficio_agrupado', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('mes', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
